### ISSUE TITLE
Add wireframe box around the system

### ISSUE THREAD

**Issue by andeplane** [ComputationalPhysics/atomify-lammps#143]
Svenn-Arne Dragly [2:37 PM]  
Entity { components: [ CubeMesh{}, Transform {}, PhongMaterial {} ] } sammen med Spheres og Bonds i AtomifyVisualizer bør fungere

[2:38]  
Må jobbe litt for å få til wireframe, men jeg tror det finnes et Qt3D-eksempel

**Comment by dragly** [comment]
Fixed in 9af7042
