### ISSUE TITLE
Fix visualization in triclinic box

### ISSUE THREAD

**Issue by andeplane** [ComputationalPhysics/atomify-lammps#165]
Should we remap everything into "normal" coordinates or not?

**Comment by andeplane** [comment]
From lammps/src/domain.h, we have access to
double corners[8][3];
which can be used.

**Comment by andeplane** [comment]
corners matrix will be filled if we first call
`lammps->domain->box_corners();`
in System::synchronize();

**Comment by dragly** [comment]
Fixed in 915b92647692090d835142b68634f1a7430f591e
