### ISSUE TITLE
Add welcome overlay when no simulation is running

### ISSUE THREAD

**Issue by andeplane** [ComputationalPhysics/atomify-lammps#176]

**Comment by andeplane** [comment]
Add a few examples here also?

**Comment by andeplane** [comment]
Added welcome overlay in 496c5e33b475b022ca70e25b46fb8cdf0f8e6687.
We need to fix
- style (dark blue color on links) 
- working examples (currently LJ doesn't do anything)
- better text

**Comment by dragly** [comment]
The welcome view needs to be properly positioned when the window is resized

**Comment by andeplane** [comment]
Style (position and colors) is ok now, but we need to add examples.
