### ISSUE TITLE
Domain slicing in visualization

### ISSUE THREAD

**Issue by henriasv** [ComputationalPhysics/atomify-lammps#18]
Preferably two sliders for each coordinate direction that can select min/max coordinates of a domain where particles are to be drawn. Other particles should be invisible. This feature will be useful for instance to see cracks in the interior of a domain. (These cracks will otherwise be hidden behind particles).

**Comment by andeplane** [comment]
Added slicing functionality where you choose a normal vector, a displacement away form origo and a slice width. Fixed in 9212ee156b6699064670e7da4b0dc3ed62119999.
