### ISSUE TITLE
Cannot open file if there is no active editor

### ISSUE THREAD

**Issue by dragly** [ComputationalPhysics/atomify-lammps#189]
Ctrl+O doesn't work if there is no active editor, which is the case on a fresh install

**Comment by andeplane** [comment]
In current implementation, no editor shouldn't be a possible state.
In a fresh install, it should automatically open new tab as seen in CodeEditorWindow.qml:66:

```
if(numOpenFiles === 0) {
   newTab()
}
```

but it obviously doesn't work :p

**Comment by andeplane** [comment]
Fixed in ce8e251538b231aee5b716b33673c689b1a6cdec
