### ISSUE TITLE
Move system in trackball

### ISSUE THREAD

**Issue by andeplane** [ComputationalPhysics/atomify-lammps#198]
We should be able to move the viewcenter in trackball navigation. This could be done by actually moving the system on the screen, effectively moving the viewcenter.

This can be achieved by adding a rectangular cube around the system (the one solving https://github.com/ovilab/atomify-lammps/issues/143) and use ObjectPicker.

**Comment by andeplane** [comment]
This works now?

**Comment by dragly** [comment]
It works by right-clicking, although it doesn't work by dragging the system cube. This can be added later.
