### ISSUE TITLE
Pressing escape should not change camera mode

### ISSUE THREAD

**Issue by dragly** [ComputationalPhysics/atomify-lammps#225]
Currently the escape button is bound to changing the camera mode. This causes the camera position to change when pressing escape. Ideally, the camera should not change, but the mouse and focus should be freed. This requires the flymode navigation to be in two states: One where camera and navigation is enabled, and one where only the camera is enabled.

**Comment by andeplane** [comment]
Isn't this fixed @dragly ?

**Comment by dragly** [comment]
Not sure. I'll check.

**Comment by andeplane** [comment]
Ping @dragly

**Comment by andeplane** [comment]
I tried to press escape in both camera modes, nothing happens, so I think it is fixed.
