### ISSUE TITLE
Left menu icons should get smaller if window height is smaller than sum of heights

### ISSUE THREAD

**Issue by andeplane** [ComputationalPhysics/atomify-lammps#277]
The icons in the left menu (View, Analyze, Edit etc) will overlap if window height gets too small. On my Mac (Macbook Pro Retina) with default resolution, this happens even with full screen (see attached screenshot), and especially if the height is smaller.

A possible solution is to make icons smaller when this happens. Add a scale factor or something.

<img width="1552" alt="screenshot 2017-01-15 18 46 22" src="https://cloud.githubusercontent.com/assets/16174/21964782/f28ad582-db52-11e6-94b2-3cee1eb6840d.png">
<img width="1552" alt="screenshot 2017-01-15 18 46 25" src="https://cloud.githubusercontent.com/assets/16174/21964781/f28a030a-db52-11e6-9376-0b26454ed90b.png">

**Comment by Foxei** [comment]
I have found a simple temporary fix which allows to use atomify lammps on laptops at least in full-screen mode. Go to the file /desktop/MainDesktop.qml and edit following values:
- at id: modeMenuContainer set "width: 80"
- at id: modeMenu replace verticalCenter by "top: parent.top"
- at same id as above add "topMargin: 120" after the "marings: 16"

Now the view menu on the left side will move upwards and everything will be a little smaller. This allows you to use the menu at low resolutions. However, it does not scale and is thus not a perfect solution for this issue.

**Comment by andeplane** [comment]
That's nice. We do want to publish this quite soon and your fix might be enough for a first version. I'll try it and see if we should do that and move this issue to 2.1

**Comment by dragly** [comment]
I'll rewrite the code for the left menu once I get the chance and make it scale properly no matter the screen resolution. It's a bit tricky, but definitely doable.
