### ISSUE TITLE
Idea: Color individual groups. 

### ISSUE THREAD

**Issue by filiphl** [ComputationalPhysics/atomify-lammps#280]
It might be nice to have the option of coloring all atoms within a group with one color. For instance group1 green and group2 purple. A challange would be to decide what to do with atoms belonging to several groups.

**Comment by andeplane** [comment]
We could add this with Atomify commands
```
#/group 1 white
#/group 2 #ffccaa
```

Next to the `Group` title in the sidebar, there could be a coloring symbol which will turn on this effect. The same happens to regions of course.

Overlapping groups/regions will be solved by just letting the order matter. So the later defined group/region will override the value of an atom.

**Comment by andeplane** [comment]
GUI not finalized yet, but if you now hover the groupbox for regions or groups, it will loop through all regions / groups and color each atom corresponding to membership.
