### ISSUE TITLE
Idea: Reading log-files

### ISSUE THREAD

**Issue by filiphl** [ComputationalPhysics/atomify-lammps#298]
Hi guys! 
I can't find any options for reading log-files! 
This could be handy, for instance when using the "print" command, and maybe also when debugging. I'm guessing it's easy to implement, so why not? 😄

**Comment by andeplane** [comment]
If atomify is run from terminal, the log is printed to console and the log is in the file anyway. Until LAMMPS has a nice way of capturing stdout we won't touch this.
