### ISSUE TITLE
Simulation speed has too many digits

### ISSUE THREAD

**Issue by anakkerud** [ComputationalPhysics/atomify-lammps#310]
Fractional target simulation speed multipliers are shown with very many significant digits.

<img width="293" alt="screen shot 2017-05-07 at 08 56 08" src="https://cloud.githubusercontent.com/assets/557578/25778596/0dd4b008-3303-11e7-9c4f-7200c65c331e.png">

EDIT: this is in App Store version

**Comment by anakkerud** [comment]
Steps to reproduce: Start application. In the default simulation, click Analyse. Use trackpad to drag speed slider. Some steps are integers, others not.

**Comment by andeplane** [comment]
Could you also provide version of macOS?

**Comment by andeplane** [comment]
I can reproduce the issue. This only happens with Qt 5.9 beta it seems.
