### ISSUE TITLE
snap package segfault on Ubuntu

### ISSUE THREAD

**Issue by beew** [ComputationalPhysics/atomify-lammps#342]
Hi, just to report that the snap package for atomify segfault in Ubuntu 16.04 and 17.04 64 bits. There is no more info in the terminal. Compiling from dev branch works though.

**Comment by beew** [comment]
This should be a separate issue but it seems that github doesn't allow me to start two new issues. The released tarball does not compile on Ubuntu 16.04 . When trying to configure from qt-creator it complains that examples/examples.qrc is missing and suggests to run  python configure.py but it has already been run successfully.

The dev branch (git clone) does compile without issue.

**Comment by andeplane** [comment]
Hi, thanks for reporting! We've had some troubles with the snap packages previously. I see that `sudo snap install atomify` installs an old version which never worked I think. I'll see if I can update it.

Could you try
`sudo snap install atomify --edge`

which will install a newer version.

**Comment by andeplane** [comment]
@dragly do you want to update new snap version?

**Comment by andeplane** [comment]
And yeah, the released tarball does not include submodules, so we could probably add another step in the configure script. Github automatically adds it there, but I know it doesn't work ;P 

Thanks!

Edit: I think `atomify-2.0.9-src.tar.gz` should work. It is manually created with the examples.

**Comment by beew** [comment]
Hi, Thanks. 
```
snap install atomify --edge 
```
works. So does compiling atomify-2.0.9-src.tar.gz

**Comment by andeplane** [comment]
Good :) snap is now updated to point to the latest (working) build.
