### ISSUE TITLE
Periodic images bug

### ISSUE THREAD

**Issue by khavernathy** [ComputationalPhysics/atomify-lammps#351]
Hi,

Thanks for some great software. I found a bug in the periodic imaging functionality. Here is a link to the video: http://supahbox.ddns.net/stuff/atomifybug.mp4

Also I'm attaching the LAMMPS input and data files.

Some notes:

Linux Ubuntu 16.04
OMP package on with 8 threads
Downloaded a few days ago

[mof5+h2.zip](https://github.com/ovilab/atomify/files/1202594/mof5.h2.zip)

**Comment by andeplane** [comment]
Hey,

thanks! I'll look into it :D
