### ISSUE TITLE
Check for OpenGL 4.3 or fall back to ES

### ISSUE THREAD

**Issue by dragly** [ComputationalPhysics/atomify-lammps#63]
Currently #version 400 fails in GLSL on systems with OpenGL 3.3 because it doesn't fall back properly to ES and non-geometry shaders instead. We need to fall back properly to ES if 4.3 isn't available.

**Comment by andeplane** [comment]
Fixed in SimVis commit c2a6d3853a9b5f69eff753dd37017920215e5536
